image: node:8.11
stages:
  - prepare
  - test
  - build
  - confidence-check
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

prepare:
  stage: prepare
  script:
    - wipCommits=`git log --grep=^WIP`; if [ -n "$wipCommits" ]; then echo "WIP commits detected; aborting."; exit 1; fi
    - npm install --ignore-scripts --frozen-lockfile
  artifacts:
    expire_in: 1 month
    paths:
    - node_modules/
test:
  stage: test
  dependencies: prepare
  script:
    - echo "\e[1;96m➜ Initializing test stage. \e[0m"
build:
  stage: test
  script:
    - echo "\e[1;96m➜ Initilizing build stage. \e[0m"
    - export CODE_BRANCH="$CI_COMMIT_REF_SLUG"
    - if [[ $CI_COMMIT_REF_NAME == $BRANCH_IN_MAINTENANCE ]]; then echo 'Building in maintenance mode.'; export MAINTENANCE_MODE=true; fi;
    - yarn run build
  artifacts:
    paths:
    - public
  only:
  - production
e2e:firefox:
  stage: confidence-check
  services:
    - selenium/standalone-firefox
  dependencies:
   - prepare
  script:
    - if [[ $CI_COMMIT_REF_NAME == $BRANCH_IN_MAINTENANCE ]]; then echo 'Running checks in maintenance mode.'; export MAINTENANCE_MODE=true; fi;
    - npm run confidence-check --host=selenium__standalone-firefox
  artifacts:
    expire_in: 1 week
    paths:
    - tests/results/
    - tests/errorShots/
    when: always
  # GUI tests loading a full browser are notoriously unstable.
  # See https://gitlab.com/Flockademic/Flockademic/issues/366
  retry: 2
e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  dependencies:
   - prepare
  script:
    - if [[ $CI_COMMIT_REF_NAME == $BRANCH_IN_MAINTENANCE ]]; then echo 'Running checks in maintenance mode.'; export MAINTENANCE_MODE=true; fi;
    - npm run confidence-check --host=selenium__standalone-chrome
  artifacts:
    expire_in: 1 week
    paths:
    - tests/results/
    - tests/errorShots/
    when: always
  # GUI tests loading a full browser are notoriously unstable.
  # See https://gitlab.com/Flockademic/Flockademic/issues/366
  retry: 2
