stages:
  - build
  - test
  - deploy
# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules
    - cache/Cypress

install:
  image: cypress/base:10
  stage: build
  script:
    - npm install

test:
  image: cypress/base:10
  stage: test
  script:
    # print CI environment variables for reference
    # - $(npm bin)/print-env CI
    - npm install
    # run Cypress test in load balancing mode, pass id to tie jobs together
    - npm run e2e
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

deploy_staging:
  stage: deploy
  image: cypress/base:10
  script:
    - npm run build
  environment:
    name: stage/$CI_COMMIT_REF_NAME
    url: https://stage.gavinvaught.com
  only:
    - staging

deploy_prod:
  stage: deploy
  image: cypress/base:10
  script:
    - npm run build
  environment:
    name: prod/$CI_COMMIT_REF_NAME
    url: https://gavinvaught.com
  only:
    - production
