image: node:latest
before-script:
    - echo "\e[0;96m > Install npm \e[0m"
    - npm install

stages:
  - test
  - build
  - deploy_staging
  - confidence-check
  - deploy
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
    - echo "\e[1;96m➜ Initializing test stage. \e[0m"
    - echo "\e[1;96m➜ Initializing test stage. \e[0m"
build:
  stage: test
  script:
    - echo "\e[1;96m➜ Initilizing build stage. \e[0m"
    - echo "\e[0;96m Installing NPM...\e[0m"
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
    - public
  only:
  - production
staging:
  stage: deploy_staging
e2e:firefox:
  stage: confidence-check
  services:
    - selenium/standalone-firefox
  script:
    - echo "\e[1;96m➜ Initializing confidence-check. \e[0m"
    - echo "\e[0;96m Installing geckodriver. \e[0m"
    - curl -L https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz | tar xz
    - npm run confidence-check --host=selenium__standalone-firefox

