stages:
  - test
  - deploy
# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

image: node:latest

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - cache/Cypress/
    - .cache/

default:
  before_script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - npm install

test:
  stage: test
  image: cypress/base:10
  script:
    # run Cypress test in load balancing mode, pass id to tie jobs together
    - npm run test
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
      - .cache
    expire_in: 7 days
  only:
    refs:
      - merge_requests
      - /^gatsby-.*$/g

deploy_staging:
  stage: deploy
  script:
    - ./node_modules/.bin/gatsby build --prefix-paths
  environment:
    name: staging
    url: https://stage.gavinvaught.com
  artifacts:
    paths:
      - .cache
  only:
    - staging

deploy_prod:
  stage: deploy
  script:
    - ./node_modules/.bin/gatsby build --prefix-paths
  environment:
    name: production
    url: https://gavinvaught.com
  artifacts:
    paths:
      - .cache
  only:
    - production
  after_script:
    - curl -X POST -d {} https://api.netlify.com/build_hooks/5df85759cd781f69f161b56c?trigger_branch=production&trigger_title=GitLab+CI+hook